#include <iostream>
#include <string>
using namespace std;

/** Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.*/

/** it is similar to find number */
class Solution{
public:
  char findTheDifference(string s, string t) {
    char Dif = 0;
    char temps = 0;
    char tempt = 0;
    for (int i = 0; i < s.size(); i++){
      temps ^= s[i];
    }
    for (int j = 0; j < t.size(); j++){
      tempt ^= t[j];
    }
    Dif = temps ^ tempt;
    return Dif;
  }
};
int main() {
  std::cout << "Hello, World!" << std::endl;
  return 0;
}